export const portData2 = [

 //===========================CARD DESIGNS DATA=======================================//
 {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/1.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/2.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/3.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/4.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/5.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/6.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/7.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/8.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/9.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/10.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/11.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/12.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/13.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/14.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/15.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/16.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/17.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/18.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/19.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/20.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/21.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/22.jpg',
    category: 'card_design',
  },
  {
    title: '',
    subtitle: '',
    href: '',
    src: '/images/portfolio_card_designs/23.jpg',
    category: 'card_design',
  },



]