export const portData6 =
[
    //===========================STOREFRONT DATA=============================//

    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/1.jpg',
        category: 'storefront_design',
    },
    // {
    //     title: '',
    //     subtitle: '',
    //     href: '',
    //     src: '/images/portfolio_store_front/2.jpg',
    //     category: 'storefront_design',
    // },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/3.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/4.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/5.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/6.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/7.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/8.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/9.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/10.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/11.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/12.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/13.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/14.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/15.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/16.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/17.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/18.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/19.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/20.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/21.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/22.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/23.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/24.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/25.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/26.jpg',
        category: 'storefront_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_store_front/27.jpg',
        category: 'storefront_design',
    },
]