export const portData5 =
[

    //==================================BRAND LOGO PORTFOLIO=============================//
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/1.jpg',
        category: 'logo_design',
    },

    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/2.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/3.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/4.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/5.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/6.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/7.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/8.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/9.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/10.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/11.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/12.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/13.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/14.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/15.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/16.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/17.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/18.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/19.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/20.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/21.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/22.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/23.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/24.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/25.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/26.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/27.jpg',
        category: 'logo_design',
    },
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/28.jpg',
        category: 'logo_design',
    },
    
    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_logo_designs/29.jpg',
        category: 'logo_design',
    },
    
    


]