export const portData4
 =
 [

    //============================EBC-A===================================================//

    {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/1.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/2.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/3.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/4.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/5.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/6.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/7.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/8.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/10.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/11.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/12.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/13.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/14.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/15.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/16.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/17.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/18.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/19.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/20.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/21.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/22.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/23.jpg',
        category: 'ebc_design',
      },
      {
        title: '',
        subtitle: '',
        href: '',
        src: '/images/portfolio_EBC_A/24.jpg',
        category: 'ebc_design',
      },
     
 ]